apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP #clusterIp are default other alternatives are node port and loadbalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port
